version: '3'
services:
  be:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/src
      - node_modules:/src/node_modules
    command: sh -c "npm start"
    environment:
      - MONGO_URI=mongodb://lab_reporter:lab_reporter1234@db:27017/lab_reporter_dev
      - MONGO_TEST_URI=mongodb://lab_reporter:lab_reporter1234@db:27017/lab_reporter_test
      - PORT=3000
      - JWT_SECRET=lab_reporter1234
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - GOOGLE_DRIVE_TEMPLATES_FOLDER_ID
      - GOOGLE_DRIVE_DELETED_TEMPLATES_FOLDER_ID
      - GOOGLE_DRIVE_REPORTS_FOLDER_ID
      - GOOGLE_DRIVE_DELETED_REPORTS_FOLDER_ID
      - BASE_URL
      - FRONTEND_URL
    depends_on:
      - db
  db:
    image: mongo:5-focal
    restart: always

    volumes:
      - ./docker-entrypoint-initdb.d/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  data:
  node_modules:
